[package]
name = "nickel"
version = "0.1.0"
authors = ["William Brandon <hypercube97@gmail.com>"]

[dependencies]
pretty-trait = "0.1.2"
nom = { version = "4.0.0-beta2", features = ["verbose-errors"] }
